package com.example.boardapipractice.dto.post

import com.example.boardapipractice.entity.Post

/**
 * DTO for creating a new post
 * Excludes the postId field which is auto-generated by the database
 */
data class PostCreateDto(
    val title: String,
    val content: String,
    val author: String,
    val password: String
) {
    /**
     * Convert DTO to Entity
     *
     * @return Post entity with default ID (0)
     */
    fun toEntity() = Post(
        title = title,
        content = content,
        author = author,
        password = password
    )
}